server:
  port: 8082

spring:
  profiles:
    active: dev
  main:
    allow-circular-references: true
  datasource:
    driver-class-name: ${hiLunch.datasource.driver-class-name}
    url: jdbc:mysql://${hiLunch.datasource.host}:${hiLunch.datasource.port}/${hiLunch.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: ${hiLunch.datasource.username}
    password: ${hiLunch.datasource.password}


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.hiLunch.entity
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com:
      sky:
        mapper: debug
        service: info
        controller: info

hilunch:
  jwt:
#admin
    # 秘密鍵
    admin-secret-key: hiLunch
    # 有効時間
    admin-ttl: 7200000
    # トークン名
    admin-token-name: token

#user
    # 秘密鍵
    user-secret-key: hiLunchUser
    # 有効時間
    user-ttl: 7200000
    # トークン名
    user-token-name: token


