hiLunch:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: hiLunch_db
    username: root
    password: root

  redis:
    host: localhost
    port: 6378
    password: 123456
  #  database: DB0



paypay:
  production-mode: false
  api-key: a_0j60HhiRh2_lhJn
  api-secret-key: nOzVvwP8rAhrmfl9g/uz/h/KqXOV1y0PWiPPAduKF7U=
  assume-merchant: 870677012170178560